function cfgHyper = InitHyperConfigs

% cfgHyper = InitHyperConfigs
%
% Initialize hyper parameter sets to initialize all analyses. This function 
% is followed by InitRandomConfigs.
%
% Sensitivity parameters contain lower limit, best estimate and upper limit
% for sensitivity analyses. Scenario parameters contain three possible values
% of fixed, but known possible scenarios. Fixed parameters are supposed 
% to be constants in analyses. Random parameters are drawn uniformly from 
% the specified range.
%
% Sensitivity:
%
% IncubationMean: Mean of Incuation time
% SymptomMean: Mean of symptomatic infectious time
% IncubationSD: Standard deviation of incubation team
% SymptomSD: Standard deviation of sympomatic infectious time
% Peak Shift: Peak infectiousness relative to symptom onset
% fracAsymp: Fraction of asymptomatic disease courses
% asympInfec_rel: Relative infectiousness of asymptomatic agents
% infectivityShape: Shape parameter in Gamma-distribution of individual
%       infectivity modifier (mean is 1)
% pInitInfec: Prevalence of currently infected in population
% R0: Average R0 as defined in secondary infections per primary infection.
%       Scales infection risk in clinic
% baseInfection: Infection risk given effective contact with an infected
%       individual. Scales infection risk outside of clinic.
% fracIso: Relative fraction of symptomatic individuals isolated each day
% excpectedFalseAlarms: Absolute number of fake symptomatic people each day
% fracTrace: Relative fraction of contacts traced successfully
% expectedFalseTraces: Maximal number of falsely traced individuals. Scales
%       with fracTrace.
% testSensitivity: Sensitivity of used diagnostic test
% testSpecificity: Specificity of used diagnostic test
% modifierRisk: Relative risk increase of risk workers
% compliance: Probability that an agent will participate in surveillance
%       testing
%
% Scenario:
%
% testDelay: Delay test to result
% retestfreq: Frequency of testing of quarantined individuals
% minQuarantine: Amount of Quarantine before first quarantine test
% maxQuarantine: Maximal amount of quarantine
%
% Fixed:
%
% probRisk: Assignment of workers to risk groups
% leaveTime: Duration of patient stay
% matrixContactStructure: Relative frequency of contacts between groups
% InfectiousShift: Range of possible presymptomatic period values
%
% Random:
% 
% nPatients: Number of patients in clinic
% nWorkers: Number of workers in clinic
% contactsAfterWork: Number of contacts of workers after work
% contactsLeave: Number of contacts of patients on weekend leave
% contactsVisit: Number of contacts of patients when visited
% fracWeekend: Fraction of patients leaving each weekend
% fractVisit: Fraction of patients getting visited on a given day

SensitivityStruct = struct(...
    'IncubationMean',[5,5.5,6],...
    'SymptomMean',[3.5,5,6.5],...
    'IncubationSD',[2.1,2.3,2.5],...
    'SymptomSD',[1.1,1.5,1.9],...
    'PeakShift',[-1,1,3],...
    'fracAsymp',[0.1,0.2,0.3],...
    'asympInfec_rel',[0.4,0.7,1],...
    'infectivityShape',[1,1.5,1000],...
    'pInitInfec',10^-4*[0.5,2,8],...
    'R0',[1.5,3,5],...
    'baseInfection',[0.01,0.04,0.16],...
    'fracIso',[0.5,0.7,0.9],...
    'expectedFalseAlarms',[0.5,1,2],...
    'fracTrace',[0.5,0.7,0.9],...
    'expectedFalseTraces',[4,8,12],...
    'testSensitivity',[0.8,0.9,1],...
    'testSpecificity',[0.98,0.995,1],...
    'modifierRisk',[2,4,6],...
    'compliance',[0.6,0.8,1]);

ScenarioStruct = struct(...
    'testDelay',[0,1,2],...
    'retestfreq',[4,6,8],...
    'minQuarantine',[1,3,5],...
    'maxQuarantine',[7,10,14]);

FixedStruct = struct(...
    'probRisk',[0.3,0.4,0.3],...
    'leaveTime',56,...
    'matrixContactStructure',0.5*[2,1,1,1;1,1,1,1;1,1,1,1;1,1,1,1],...
    'InfectiousShift',[-4,-1]);

RandomStruct = struct(...
    'nPatients',[50,60],...
    'nWorkers',[80,100],...
    'contactsAfterWork',[0.2,1],...
    'contactsLeave',[1,3],...
    'contactsVisit',[0.5,1.5],...
    'fracWeekend',[0.1,0.2],...
    'fracVisit',[0.01,0.03]);
    
cfgHyper = struct('Sensitivity',SensitivityStruct,...
    'Scenario',ScenarioStruct,'Uniform',RandomStruct,'Fixed',FixedStruct);    

end

