% Final Triple Result Plot:
% Test-to-Result Delay, Outbreak Size, Compliance and Test Frequency
%
% Combines the plots generated by the corresponding subfunctions

f = figure('Position',[150,150,1400,500]);
subs = gobjects(1,3);

% Load and create all three result plots
subs(1) = subplot(1,3,1);
load('TestDelaySerious35Data.mat')
FFPlotDelay(Outbreak_tot3,1);
subs(2) = subplot(1,3,2);
load('StepAnalysis.mat')
FFPlotOutbreakPoints;
subs(3) = subplot(1,3,3);
load('FreqSys35Data.mat');
FFPlotFreq(Outbreak_tot3,'compliance',1);

clearvars -EXCEPT f subs

legend(subs(1),'off');

% Modify horizontal size and position of subplots:
pos = cell2mat(get(subs,'Position'));
siz = pos(1,3); % horizontal size of plot 1
dis = pos(2,1) - pos(1,1) - siz; % empty space between plots
siz_mod = 0.1;
dis_mod = 0.3;

pos(1,3) = (1-siz_mod)*siz; % Shrink plot1
pos(2,3) = (1-siz_mod)*siz; % Shrink plot2
pos(3,3) = (1+2*siz_mod)*siz+2*dis_mod*dis; % Enlargen plot3
pos(2,1) = pos(1,1) + (1-dis_mod)*dis+(1-siz_mod)*siz; % Shift plot2
pos(3,1) = pos(2,1) + (1-dis_mod)*dis+(1-siz_mod)*siz; % Shift plot3

txts = {'A: ','B: ','C: '};
ylims = [];
for ii = 1:3
    axes(subs(ii));
    title_tmp = get(subs(ii),'Title');
    set(title_tmp,'String',[txts{ii},get(title_tmp,'String')],...
        'FontSize',14) % Modify title
    set(subs(ii),'Position',pos(ii,:)); % Set new positions
    
    % Match y-axis limits:
    ylims_tmp = get(subs(ii),'YLim');
    if isempty(ylims)
        ylims = ylims_tmp; 
    else
        ylims(1) = min([ylims(1),ylims_tmp(1)]);
    end
    
    % Aesthetic changes:
    xaxis_handle = get(subs(ii),'XAxis');
    set(xaxis_handle,'FontSize',11,'Linewidth',1.1);
    yaxis_handle = get(subs(ii),'YAxis');
    set(yaxis_handle,'FontSize',11,'LineWidth',1.1);
    xlab_handle = get(subs(ii),'XLabel');
    set(xlab_handle,'FontSize',13);
    ylab_handle = get(subs(ii),'YLabel');
    set(ylab_handle,'FontSize',13);
    leg = get(subs(ii),'Legend');
    set(leg,'FontSize',10,'AutoUpdate','off');
    xlims = get(subs(ii),'XLim');
    line(subs(ii),xlims,[0,0],'LineWidth',2,...
        'LineStyle','--','Color',[0,0,0]);
    set(subs(ii),'GridAlpha',0.3)
end
set(subs,'YLim',[-5.1,0.1]); % Manual correction
ylabel(subs(2),'');
ylabel(subs(3),'');
