function newnames = RemapNames(whichnames,varname)
% newnames = RemapNames(whichnames,varname)
%
% Maps model internal parameter names to "nice" parameter names for
% figures.
%
% whichnames: Parameter names to be replaced
% varname: If 0 is used, parameter names are displayed without symbols.
%               Conversely, any other value means thaht parameter symbols
%               are displayed next to parameter names.

if ~exist('varname','var')
    varname = 0;
end

newnames = cell(size(whichnames));

% List of old names ("domain")
mapdom = {'IncubationMean','SymptomMean','IncubationSD','SymptomSD',...
    'PeakShift','fracAsymp','asympInfec_rel',...
    'infectivityShape','pInitInfec','R0','baseInfection',...
    'fracIso','expectedFalseAlarms',...
    'fracTrace','expectedFalseTraces',...
    'testSensitivity','testSpecificity',...
    'modifierRisk','compliance'};
    
% List of new names ("image")
if varname == 0
    % ... without symbols
    mapimg = {'IncubationMean','SymptomMean','IncubationSD','SymptomSD',...
        'PeakInfectiousness','AsymptomaticFraction','AsymptomaticInfectivity',...
        'InfectivityHeterogeneity','Prevalence','R0','OutsideInfection',...
        'IsolationFraction','FalseSymptoms',...
        'TracingFraction','FalseTraces',...
        'TestSensitivity','TestSpecificity',...
        'HeterogeneityModifier','TestCompliance'};
else
    % ... with symbols
    mapimg = {'IncubationMean \mu_{inc}','SymptomMean \mu_{symp}',...
        'IncubationSD \sigma_{inc}','SymptomSD \sigma_{symp}',...
        'PeakInfectiousness \sl t_{peak}','AsymptomaticFraction \sl A',...
        'AsymptomaticInfectivity \sl A_{rel}','InfectivityHeterogeneity \beta',...
        'Prevalence \sl P_{prev}','\sl R_0','OutsideInfection \sl P_{I|C}',...
        'IsolationFraction \sl p_{symp}','FalseSymptoms \sl F_{symp}',...
        'TracingFraction \sl p_{trace}','FalseTraces \sl F_{trace}',...
        'TestSensitivity','TestSpecificity',...
        'HeterogeneityModifier \sl h_{mod}','TestCompliance'};    
end

% Check list of given names and make list of new names
for ii = 1:length(newnames)
   q_tmp = strcmp(whichnames{ii},mapdom);
   newnames{ii} = mapimg{q_tmp};
end

end

